//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İNTEKO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive_Customers
    {
        public int Id { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> Username { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
