//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İNTEKO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        public int Id { get; set; }
        public string CustomerNameSurname { get; set; }
        public string CompanyName { get; set; }
        public string Installer { get; set; }
        public string ProccessType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Payment_Amount { get; set; }
        public Nullable<double> PaymentPaid { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.DateTime> LogUpdateDate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Voen { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual BonusFiles BonusFiles { get; set; }
    }
}
