//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İNTEKO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int Id { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Elave2FileName { get; set; }
        public string Elave2FileExtensions { get; set; }
        public byte[] Elave2Data { get; set; }
    }
}
