//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İNTEKO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IntekodbEntities : DbContext
    {
        public IntekodbEntities()
            : base("name=IntekodbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PaymentType> PaymentType { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Kassalar> Kassalar { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<PaymentHistory> PaymentHistory { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Tarifler> Tarifler { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Bonus> Bonus { get; set; }
        public virtual DbSet<LicenceHistory> LicenceHistory { get; set; }
        public virtual DbSet<BonusFiles> BonusFiles { get; set; }
        public virtual DbSet<LicenceVersions> LicenceVersions { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Problems> Problems { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Archive_Customers> Archive_Customers { get; set; }
    
        public virtual ObjectResult<string> ExpensesProcNo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ExpensesProcNo");
        }
    }
}
