//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İNTEKO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public Nullable<int> UsersID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<double> TotalPaid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ExNo { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Users Users { get; set; }
    }
}
