//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İNTEKO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        public int Id { get; set; }
        public string QaimeNo { get; set; }
        public Nullable<double> PaymentTotal { get; set; }
        public Nullable<double> PaymentPaid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Avans { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> PaymentID { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Payments Payments { get; set; }
    }
}
